version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: industrial_db
    environment:
      POSTGRES_USER: industrial
      POSTGRES_PASSWORD: industrial123
      POSTGRES_DB: industrial_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: