spring.application.name=industrial-api

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/industrial_api
spring.datasource.username=industrial
spring.datasource.password=industrial123

# JPA settings
# Auto crea/actualiza las tablas desde las entidades (NO USAR EN PRODUCCION)
spring.jpa.hibernate.ddl-auto=update
# Saca las Queries SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect